[versions]
agp = "8.9.0"
okhttp = "4.12.0"
shizuku-api = "13.1.5"
shizuku-provider = "13.1.5"
json = "20231013"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lz4Java = "1.8.0"
material = "1.12.0"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku-api" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku-provider" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lz4-java = { module = "org.lz4:lz4-java", version.ref = "lz4Java" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

